# Generated by Django 5.2.5 on 2025-08-18 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_about_adminrole_adminuser_admininvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_invitations', to='api.adminuser'),
        ),
        migrations.AddField(
            model_name='admininvitation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admininvitation',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_invitations', to='api.adminuser'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position',
            field=models.CharField(default='N/A/', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
