# Generated by Django 5.2.5 on 2025-08-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admininvitation_accepted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
