# Generated by Django 5.2.5 on 2025-08-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='first_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='last_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
    ]
