# Generated by Django 5.2.5 on 2025-08-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_about_first_name_about_last_name_about_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ('site_name', 'site_logo', 'site_favicon', 'site_description', 'site_keywords', 'site_author', 'site_email', 'site_phone', 'site_address', 'site_city', 'site_state', 'site_zip', 'site_country', 'site_copyright', 'site_github', 'site_linkedin', 'site_twitter', 'site_instagram', 'site_facebook', 'site_youtube', 'site_tiktok', 'site_pinterest', 'site_reddit'), 'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.RemoveField(
            model_name='setting',
            name='key',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='value',
        ),
        migrations.AddField(
            model_name='adminrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='experience/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_address',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_author',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_city',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_copyright',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_country',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_description',
            field=models.TextField(default='n/a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_email',
            field=models.EmailField(default='n/a', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_keywords',
            field=models.TextField(default='n/a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_name',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_phone',
            field=models.CharField(default='n/a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_pinterest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_reddit',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_state',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_zip',
            field=models.CharField(default='n/a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
    ]
