# Generated by Django 5.2.5 on 2025-08-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_setting_options_remove_setting_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('page_engagement', 'Page Engagement'), ('click', 'Click Tracking'), ('form', 'Form Interaction'), ('performance', 'Performance Metric'), ('session', 'Session Data'), ('custom', 'Custom Metric')], max_length=50)),
                ('page', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Analytics Metric',
                'verbose_name_plural': 'Analytics Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['type', 'timestamp'], name='api_analyti_type_adf3e9_idx'), models.Index(fields=['page', 'timestamp'], name='api_analyti_page_d68df7_idx'), models.Index(fields=['timestamp'], name='api_analyti_timesta_06d0b1_idx')],
            },
        ),
    ]
