# Generated by Django 5.2.5 on 2025-08-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_analyticsmetric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsMetric',
        ),
    ]
