# Generated by Django 5.2.5 on 2025-09-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_analyticsmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='education/'),
        ),
        migrations.AddField(
            model_name='education',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
