# Generated by Django 5.2.5 on 2025-09-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_education_certificate_education_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
