# backend/portfolio/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ProjectList,
    SkillList,
    ExperienceList,
    EducationList,
    AboutList,
    ContactCreate,
    TestimonialList,
    SocialLinkList,
    SettingList,
    ServiceList,
    # Admin ViewSets for authenticated users
    ProjectAdminViewSet,
    SkillAdminViewSet,
    ExperienceAdminViewSet,
    EducationAdminViewSet,
    AboutAdminViewSet,
    ContactAdminViewSet,
    TestimonialAdminViewSet,
    SocialLinkAdminViewSet,
    SettingAdminViewSet,
    ServiceAdminViewSet,
    # New admin management ViewSets
    AdminRoleViewSet,
    AdminUserViewSet,
    AdminInvitationViewSet,
    accept_invitation,
    validate_invitation,
    get_current_admin_user,
    get_analytics_data,
    health_check
)

# Initialize the router for all admin-level endpoints.
# The `DefaultRouter` automatically generates standard API paths
# (e.g., list, create, retrieve, update, delete).
router = DefaultRouter()
router.register(r'admin/projects', ProjectAdminViewSet, basename='project-admin')
router.register(r'admin/skills', SkillAdminViewSet, basename='skill-admin')
router.register(r'admin/experiences', ExperienceAdminViewSet, basename='experience-admin')
router.register(r'admin/educations', EducationAdminViewSet, basename='education-admin')
router.register(r'admin/about', AboutAdminViewSet, basename='about-admin')
router.register(r'admin/contacts', ContactAdminViewSet, basename='contact-admin')
router.register(r'admin/testimonials', TestimonialAdminViewSet, basename='testimonial-admin')
router.register(r'admin/sociallinks', SocialLinkAdminViewSet, basename='sociallink-admin')
router.register(r'admin/settings', SettingAdminViewSet, basename='setting-admin')
router.register(r'admin/services', ServiceAdminViewSet, basename='service-admin')

# Admin Management URLs
router.register(r'admin-roles', AdminRoleViewSet)
router.register(r'admin-users', AdminUserViewSet)
router.register(r'admin-invitations', AdminInvitationViewSet)

# Define the public-facing, read-only API endpoints.
# These views will be accessible to all users.
public_urlpatterns = [
    path('projects/', ProjectList.as_view(), name='project-list'),
    path('skills/', SkillList.as_view(), name='skill-list'),
    path('experiences/', ExperienceList.as_view(), name='experience-list'),
    path('educations/', EducationList.as_view(), name='education-list'),
    path('about/', AboutList.as_view(), name='about-list'),
    path('contacts/', ContactCreate.as_view(), name='contact-create'),
    path('testimonials/', TestimonialList.as_view(), name='testimonial-list'),
    path('sociallinks/', SocialLinkList.as_view(), name='sociallink-list'),
    path('settings/', SettingList.as_view(), name='setting-list'),
    path('services/', ServiceList.as_view(), name='service-list'),
]

# Combine the public URLs with the admin URLs generated by the router.
# The `router.urls` property returns a list of URL patterns.
urlpatterns = [
    path('', include(router.urls)),
    path('accept-invitation/', accept_invitation, name='accept_invitation'),
    path('validate-invitation/', validate_invitation, name='validate_invitation'),
    path('current-admin-user/', get_current_admin_user, name='current_admin_user'),
    path('analytics/', get_analytics_data, name='analytics_data'),
    path('health/', health_check, name='health_check'),
] + public_urlpatterns
